name: Invite Cameroonian Developers

on:
  schedule:
    # Run every 3 days at 00:00 UTC
    - cron: "0 0 */3 * *"
  # Allow manual triggering
  workflow_dispatch:

jobs:
  invite-developers:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      repository-projects: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub requests

      - name: Create directories
        run: |
          mkdir -p data
          mkdir -p .github/scripts

      - name: Download Cameroon developers list
        run: |
          curl -o data/cameroon.md https://raw.githubusercontent.com/gayanvoice/top-github-users/main/markdown/public_contributions/cameroon.md

      - name: Run invitation script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python .github/scripts/invite_cameroon_devs.py

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/
          git commit -m "Update invitation records" -a || echo "No changes to commit"
          git push
